kind: pipeline
name: default

steps:
- name: isort
  image: python:alpine
  commands:
  - pip install isort
  - isort --check-only --diff .
- name: pylint
  image: alpine
  commands:
  - apk add --no-cache python3 py3-lxml py3-pip py3-wheel
  - pip3 install --no-cache-dir .
  - pylint morss --rcfile=.pylintrc --disable=C,R,W --fail-under=8
